Garage2.0_Group5/Models/Entities/Receipt.cs
namespace Garage2._0_Group5.Models.Entities
{
    public class Receipt
    {
        public int Id { get; set; }
        public string RegistrationNumber { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public TimeSpan TotalParkedTime { get; set; }
        public double ParkPrice { get; set; }
    }
}

Garage2.0_Group5/Models/ViewModels/Receipt.cs
namespace Garage2._0_Group5.Models.ViewModels
{
    public class Receipt
    {
        public int Id { get; set; }
        public string RegistrationNumber { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public TimeSpan TotalParkedTime { get; set; }
        public double ParkPrice { get; set; }
    }
}

Garage2.0_Group5/Models/ViewModels/ReceiptViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Garage2._0_Group5.Models.ViewModels
{
    public class ReceiptViewModel
    {
        public string ID { get; set; }
        [DisplayName("Departure Time")]
        public DateTime DepartureTime { get; set; }

        [DisplayName("Total Time")]
        [DisplayFormat(DataFormatString = "{0:hh\\:mm\\:ss}", ApplyFormatInEditMode = true)]
        public TimeSpan TotalTime { get; set; }

        [DisplayName("Price (2 kr / min)")]
        public double Price { get; set; }

    }
}

Garage2.0_Group5/Controllers/Vehicles2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Garage2._0_Group5.Data;
using Garage2._0_Group5.Models.Entities;
using jsreport.AspNetCore;
using jsreport.Types;
using Garage2._0_Group5.Models.ViewModels;
using AutoMapper;

namespace Garage2._0_Group5.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly Garage2_0_Group5Context _context;
        //private readonly IMapper _mapper;

        //public VehiclesController(Garage2_0_Group5Context context, IMapper mapper)
        public VehiclesController(Garage2_0_Group5Context context)
        {
            _context = context;
            //_mapper = mapper;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {

            var model = _context.Vehicle.AsNoTracking()
                .Select(v => new VehicleIndexViewModel
                {
                    //TypeOfVehicle = v.VehicleType.TypeOfVehicle,
                    LicenseNumber = v.LicenseNumber,
                    TimeOfRegistration = v.TimeOfRegistration,
                });

            return View(await model.ToListAsync());


            //var entities = _context.Vehicle.ToList(); // Replace YourEntities with your actual entity DbSet

            //// Map entities to view models
            //var viewModels = entities.Select(e => new VehicleIndexViewModel
            //{
            //    Id = e.Id,
            //    TypeOfVehicle = e.VehicleType.TypeOfVehicle,
            //    LicenseNumber = e.LicenseNumber,
            //    TimeOfRegistration = e.TimeOfRegistration
            //    // Map other properties as needed
            //}).ToList();

            //return _context.Vehicle != null ?
            //            View(viewModels) :
            //            Problem("Entity set 'Garage2_0_Group5Context.Vehicle'  is null.");

        }


        //public async Task<IActionResult> Filter(string id, int? type, int? noOfWheels)
        //{
        //    var model = string.IsNullOrWhiteSpace(id) ?
        //            _context.Vehicle :
        //            _context.Vehicle.Where(m => m.LicenseNumber.StartsWith(id));

        //public async Task<IActionResult> Filter(int id, int? type, int? noOfWheels)
        //{
        //    var model = int.IsNullOrWhiteSpace(id) ?
        //            _context.Vehicle :
        //            _context.Vehicle.Where(m => m.Id.StartsWith(id));

        //    //    var model = string.IsNullOrWhiteSpace(id) ?
        //    //_context.Vehicle :
        //    //_context.Vehicle.Where(m => m.ID.StartsWith(id));

        //    //model = noOfWheels is null ?
        //    //  _context.Vehicle :
        //    //  _context.Vehicle.Where(m => m.NoOfWheels.Equals(noOfWheels));

        //    model = type is null ?
        //            model :
        //            model.Where(m => (int)m.Type == type);

        //    return View(nameof(Index), await model.ToListAsync());
        //}

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null || _context.Vehicle == null)
        //    {
        //        return NotFound();
        //    }

        //    var vehicle = await _context.Vehicle
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (vehicle == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(vehicle);
        //}

        // GET: Vehicles/Create
        public IActionResult Create(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehicleCreateViewModel viewModel)
        {


            if (ModelState.IsValid)
            {
                var member = _context.Member.FirstOrDefault(member => member.Id == viewModel.MemberId);
                var vehicle = new Vehicle
                {
                    //MemberId = viewModel.MemberId,
                    LicenseNumber = viewModel.LicenseNumber,
                    Color = viewModel.Color,
                    Brand = viewModel.Brand,
                    Model = viewModel.Model,
                    TimeOfRegistration = viewModel.TimeOfRegistration,

                    //VehicleType = new VehicleType
                    //{
                    //    TypeOfVehicle = viewModel.TypeOfVehicle,
                    //    Wheels = viewModel.Wheels,
                    //}

                };
                vehicle.Member = member;


                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }

        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,Color,Brand,Model,NoOfWheels,TimeOfRegistration")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehicle == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehicle == null)
            {
                return Problem("Entity set 'Garage2_0_Group5Context.Vehicle'  is null.");
            }
            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle != null)
            {
                _context.Vehicle.Remove(vehicle);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return (_context.Vehicle?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> Receipt(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var vehicle = await _context.Vehicle
                .FirstOrDefaultAsync(m => m.Id == id);

            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        [MiddlewareFilter(typeof(JsReportPipeline))]
        public async Task<IActionResult> Print(int id)
        {
            var vehicle = await _context.Vehicle
                .FirstOrDefaultAsync(m => m.Id == id);

            HttpContext.JsReportFeature().Recipe(Recipe.ChromePdf);
            return View(vehicle);

        }

        private bool VehicleModelExists(int id)
        {
            return _context.Vehicle.Any(e => e.Id == id);
        }

        //Action method that returns a custom error message about Uniqueness of Licence Number
        [AcceptVerbs("GET", "POST")]

        public IActionResult UniqueLicenseNumber(string registrationNum)
        {
            if (_context.Vehicle.Any(v => v.LicenseNumber == registrationNum))

            {
                return Json($"This registration number {registrationNum} is already in use.");

            }
            return Json(true);
        }
    }
}

Garage2.0_Group5/ViewComponents/ReceiptViewComponent.cs
using Garage2._0_Group5.Data;
using Garage2._0_Group5.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Garage2._0_Group5.ViewComponents
{
    public class ReceiptViewComponent : ViewComponent
    {
        private readonly Garage2_0_Group5Context db;

        public ReceiptViewComponent(Garage2_0_Group5Context db)
        {
            this.db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(int vehicleId)
        {
            var vehicle = await db.Vehicles.Where(v => v.Id == vehicleId).FirstOrDefaultAsync();

            var departureTime = DateTime.Now;
            var total = departureTime - vehicle.TimeOfRegistration;
            var price = Math.Round(total.TotalMinutes * 2);

            var model = new ReceiptViewModel
            {
                DepartureTime = departureTime,
                TotalTime = total,
                Price = price
            };

            return View(model);
        }
    }
}

Garage2.0_Group5/Views/Vehicles2/Create.cshtml
@model VehicleCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Park new Vehicle</h1>

<a asp-action="Index" class="btn btn-outline-info mx-3">Back to List</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
         @*    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Member" class="control-label"></label>
                <partial name="_MemberInput" for="Member" />
                <input id="memberAutocompelete" type="text" class="form-control" />
                <input asp-for="MemberId" type="hidden" />
                <span asp-validation-for="Member.Id" class="text-danger"></span>
            </div> *@
            <input asp-for="MemberId" type="hidden" value="@ViewBag.Id" />
             <div class="form-group">
                <label asp-for="TypeOfVehicle" class="control-label"></label>
             @*    <select class="form-control" name="type" asp-items="@Html.GetEnumSelectList<TypeOfVehicle>()"> 
                    <option selected="selected" value=""> - Please Select Type - </option>
                </select> *@
                <input asp-for="TypeOfVehicle" class="form-control" />
            <span asp-validation-for="TypeOfVehicle" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="LicenseNumber" class="control-label"></label>
                <input asp-for="LicenseNumber" class="form-control" />
                <span asp-validation-for="LicenseNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
               <label asp-for="Color" class="control-label"></label>               
                <select class="form-control" name="color" asp-items="@Html.GetEnumSelectList<Color>()">
                    <option selected="selected" value=""> - Please Select Color - </option>
                </select>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wheels" class="control-label"></label>
                <input asp-for="Wheels" class="form-control" />
                <span asp-validation-for="Wheels" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Park Vehicle" class="btn btn-primary" />              
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage2.0_Group5/Views/Vehicles2/Delete.cshtml
@model Vehicle

@{
    ViewData["Title"] = "Delete";
}

<h1>Check out Vehicle</h1>

<h4>Are you sure you want to check out this vehicle?</h4>
<a asp-action="Index" class="btn btn-outline-info mx-3">No! - Back to List</a>
<div>
    <hr />
    @* <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
<<<<<<< HEAD
            @Html.DisplayNameFor(model => model.LicenseNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LicenseNumber)
=======
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
>>>>>>> Samuel_Garage3.0
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfWheels)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoOfWheels)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeOfRegistration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeOfRegistration)
        </dd>
    </dl> *@
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete">Check out Vehicle</button>

        <div class="container">
            <div class="modal fade" id="delete" role="dialog">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Would you like a Receipt?</h4>
                        </div>
                        <div class="modal-body">

                            <input type="submit" class="btn btn-primary" asp-action="Print" asp-route-id="@Model.Id" formtarget="_blank" value="Yes" />
                            <input type="submit" class="btn btn-danger" asp-action="Delete" value="No" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-bs-dismiss="modal">Go Back</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@* <input type="submit" class="btn btn-primary" asp-action="Receipt" asp-route-id="@Model.ID" formtarget="_blank" value="Yes" /> *@

Garage2.0_Group5/Views/Vehicles2/Details.cshtml
@model VehicleDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Vehicle Details</h1>

<div>
    <a asp-action="Index" class="btn btn-outline-info mx-3">Back to List</a>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfVehicle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfVehicle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LicenseNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LicenseNumber)
         </dt>

        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Model)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Model)
        </dd>
        
           @*  @if (Model.TypeOfVehicle.   Model.VehicleType.Wheels > 0)
            {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.TypeOfVehicle.whe VehicleType.Wheels)

        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.VehicleType.Wheels)
        </dd>
            } *@
            
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeOfRegistration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeOfRegistration)
        </dd>


    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-outline-info">Edit</a> *@
    @* <a asp-action="Index">Back to List</a> *@
</div>

Garage2.0_Group5/Views/Vehicles2/Edit.cshtml
@model Vehicle

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Vehicle</h1>

<a asp-action="Index" class="btn btn-outline-info mx-3">Back to List</a>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                @* <label asp-for="Type" class="control-label"></label> *@
              
@*                 <select class="form-control" name="type" asp-items="@Html.GetEnumSelectList<TypeOfVehicle>()">
                    <option selected="selected">@Model.Type</option>
                </select> *@
                @* <span asp-validation-for="Type" class="text-danger"></span> *@
            </div>
<<<<<<< HEAD
     @*        <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div> *@
=======
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
>>>>>>> Samuel_Garage3.0
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
               
                <select class="form-control" name="color" asp-items="@Html.GetEnumSelectList<Color>()">
                    <option selected="selected">@Model.Color</option>
                </select>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
      @*       <div class="form-group">
                <label asp-for="VehicleType.Wheels" class="control-label"></label>
                <input asp-for="VehicleType.Wheels" class="form-control" />
                <span asp-validation-for="VehicleType.Wheels" class="text-danger"></span>
            </div> *@
            <div class="form-group">
<<<<<<< HEAD
                <label asp-for="TimeOfRegistration" class="control-label"></label>
                <input asp-for="TimeOfRegistration" class="form-control" />
                <span asp-validation-for="TimeOfRegistration" class="text-danger"></span>
=======

>>>>>>> Samuel_Garage3.0
                @Html.DisplayNameFor(model => model.TimeOfRegistration)
                <div row class="unEditable">

                    @Html.DisplayFor(model => model.TimeOfRegistration)
                </div>
            </div>
            <div class="form-group">
<<<<<<< HEAD
                <input type="submit" value="Save" class="btn btn-primary my-3" />           
=======
                
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#delete">Save</button>

                <div class="container">
                    <div class="modal fade" id="delete" role="dialog">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Vehicle Updated!</h4>
                                </div>
                                <div class="modal-body">
                                    <input type="submit" class="btn btn-primary" asp-action="Index" asp-route-id="@Model.Id" value="Ok" />                                 
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-bs-dismiss="modal">Go Back</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
>>>>>>> Samuel_Garage3.0
            </div>
        </form>
    </div>
</div>

<div>
    @* <a asp-action="Index">Back to List</a> *@
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Garage2.0_Group5/Views/Vehicles2/Index.cshtml
@model IEnumerable<VehicleIndexViewModel>

@{
	ViewData["Title"] = "Index";
}

<h1>Parked Cars</h1>

<p>
	<a asp-action="Create" class="btn btn-outline-info mx-3">Park New Vehicle</a> 
</p>

<form asp-action="Filter" asp-controller="Vehicles" method="get">
	<div class="input-group mb-3">
		@* <input type="text" class="form-control" name="id" placeholder="Search on License Number..." /> *@
		@* <input type="text" class="form-control" name="noOfWheels" placeholder="Search on Number of Wheels..." /> *@
		

@* 		<div class="input-group-append">
			<select class="form-control" name="type" asp-items="@Html.GetEnumSelectList<TypeOfVehicle>()">
				<option selected="selected" value="">Vehicle Type...</option>
			</select>
		</div> *@


@* 		<div class="input-group-append">
			<button type="submit" class="btn btn-primary"><i class="fa fa-search">Search</i></button>
		</div> *@
	</div>
</form>


<partial name="_VehicleList" />

Garage2.0_Group5/Views/Vehicles2/Print.cshtml
@model Vehicle

@{
    ViewData["Title"] = "Vehicle Receipt";
}

<h1>Vehicle Receipt</h1>

<div>
    <dl class="row">
        <hr class="col-sm-6" />
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.LicenseNumber)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.LicenseNumber)
            </dd>
        </dl>
        <hr class="col-sm-6" />
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.TimeOfRegistration)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.TimeOfRegistration)
            </dd>
        </dl>
        <hr class="col-sm-6" />
        <vc:receipt vehicle-id="@Model.Id" />
    </dl>
</div>

Garage2.0_Group5/Views/Vehicles2/Receipt.cshtml
@model Vehicle

@{ 
    ViewData["Title"] = "Receipt";
}

<div>
    <dl class="row">
        <hr class="col-sm-6" />
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.LicenseNumber)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.LicenseNumber)
            </dd>
        </dl>
        <hr class="col-sm-6" />
        <dl class="row">
            <dt class="col-sm-3">
                @Html.DisplayNameFor(model => model.TimeOfRegistration)
            </dt>
            <dd class="col-sm-6">
                @Html.DisplayFor(model => model.TimeOfRegistration)
            </dd>
        </dl>
        <hr class="col-sm-6" />
        <vc
        <vc:receipt vehicle-id="@Model.Id" />
    </dl>
</div>

<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-info mt-3">Previous Page</button>
    <input type="submit" asp-action="Print" formtarget="_blank" class="btn btn-primary mt-3" value="Print"/>
</form>

Garage2.0_Group5/Views/Vehicles2/_VehicleList.cshtml
@model IEnumerable<VehicleIndexViewModel>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.TypeOfVehicle)
			</th>
			<th>				
				License Number
			</th>
			<th>
				Check-in Time
			</th>
			<th>Options</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.TypeOfVehicle)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.LicenseNumber)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.TimeOfRegistration)
				</td>

				<td>
					<a asp-action="Edit" asp-route-id="@item.Id" class="btn px-2 py-0 my-0 btn-light">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id" class="btn px-2 py-0 my-0 btn-light">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id" class="btn px-2 py-0 my-0 btn-light">Check Out</a>
				</td>
			</tr>
		}
	</tbody>
</table>